#ifndef _CONSTS_HPP
#define _CONSTS_HPP

#define TILE_WIDTH 32
#define TILE_HEIGHT 32

#define WINDOW_WIDTH 1024
#define WINDOW_HEIGHT 600

#define GUI_FONT_NAME "fonts/fixedsys.ttf"
#define GUI_MENU_WIDTH 800
#define GUI_MENU_HEIGHT 400
#define GUI_NONOGRAM_CELL_SIZE 32
#define GUI_SHOP_WIDTH 600
#define GUI_SHOP_HEIGHT 400

#define DIRECTION_UP 0
#define DIRECTION_DOWN 1
#define DIRECTION_LEFT 2
#define DIRECTION_RIGHT 3

#endif